[package]
name = "stm32l432x"
version = "0.1.0"
build = "build.rs"

[build-dependencies]
bobbin-build = { path = "../../../lib/bobbin-build/" }

[dependencies]
stm32-common = { path = "../stm32-common" }

[features]
default = []

STM32L432xB = []
STM32L432xC = []
