[package]
name = "stm32f40x"
version = "0.1.0"
build = "build.rs"

[build-dependencies]
bobbin-build = { path = "../../bobbin-build/" }

[dependencies]
stm32-common = { path = "../stm32-common" }

[features]
default = []

STM32F405xE = []
STM32F405xG = []
STM32F407xE = []
STM32F407xG = []
STM32F415xG = []
STM32F417xE = []
STM32F417xG = []
